# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media_processing.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'media_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16media_processing.proto\x12\x05media\".\n\x0cMediaRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"J\n\rMediaResponse\x12\x16\n\x0eprocessed_file\x18\x01 \x01(\x0c\x12\x10\n\x08mimetype\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\x90\x01\n\x0eMediaProcessor\x12\x39\n\x0cProcessMedia\x12\x13.media.MediaRequest\x1a\x14.media.MediaResponse\x12\x43\n\x12ProcessMediaStream\x12\x13.media.MediaRequest\x1a\x14.media.MediaResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIAREQUEST']._serialized_start=33
  _globals['_MEDIAREQUEST']._serialized_end=79
  _globals['_MEDIARESPONSE']._serialized_start=81
  _globals['_MEDIARESPONSE']._serialized_end=155
  _globals['_MEDIAPROCESSOR']._serialized_start=158
  _globals['_MEDIAPROCESSOR']._serialized_end=302
# @@protoc_insertion_point(module_scope)
