# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import media_processing_pb2 as media__processing__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in media_processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMedia = channel.unary_unary(
                '/media.MediaProcessor/ProcessMedia',
                request_serializer=media__processing__pb2.MediaRequest.SerializeToString,
                response_deserializer=media__processing__pb2.MediaResponse.FromString,
                _registered_method=True)
        self.ProcessMediaStream = channel.stream_stream(
                '/media.MediaProcessor/ProcessMediaStream',
                request_serializer=media__processing__pb2.MediaRequest.SerializeToString,
                response_deserializer=media__processing__pb2.MediaResponse.FromString,
                _registered_method=True)


class MediaProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessMediaStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMedia,
                    request_deserializer=media__processing__pb2.MediaRequest.FromString,
                    response_serializer=media__processing__pb2.MediaResponse.SerializeToString,
            ),
            'ProcessMediaStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessMediaStream,
                    request_deserializer=media__processing__pb2.MediaRequest.FromString,
                    response_serializer=media__processing__pb2.MediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'media.MediaProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('media.MediaProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/media.MediaProcessor/ProcessMedia',
            media__processing__pb2.MediaRequest.SerializeToString,
            media__processing__pb2.MediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessMediaStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/media.MediaProcessor/ProcessMediaStream',
            media__processing__pb2.MediaRequest.SerializeToString,
            media__processing__pb2.MediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
